# Generated by Django 2.2.5 on 2019-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default="don't read this book"),
            preserve_default=False,
        ),
    ]
